"""add_notifications

Revision ID: 4e3af3e04100
Revises: 3dd0d76db0ae
Create Date: 2026-07-09 22:21:51.107357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3af3e04100'
down_revision: Union[str, Sequence[str], None] = '3dd0d76db0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pref_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pref_slack', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pref_push', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pref_push')
    op.drop_column('users', 'pref_slack')
    op.drop_column('users', 'pref_email')
    # ### end Alembic commands ###
